services:
  db:
    image: mysql:8.4
    container_name: reminders-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: reminders
      MYSQL_USER: root1
      MYSQL_PASSWORD: Dzee2015$
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Kolkata

    ports:
      - "3307:3306"
    volumes:
      - ./mysql_db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot1 -pDzee2015$ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "7"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reminders-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://reminders-db:3306/reminders?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
      DB_USERNAME: root1
      DB_PASSWORD: Dzee2015$
      MAIL_USERNAME: ${MAIL_USERNAME:-sr.aivante@gmail.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-izcvacevlkylvwyn}
      MAIL_FROM: ${MAIL_FROM:-sr.aivante@gmail.com}
      MAIL_SSL_TRUST: ${MAIL_SSL_TRUST:-smtp.gmail.com}
      WHATSAPP_FROM: ${WHATSAPP_FROM:-+919953035570}
      TZ: Asia/Kolkata
    ports:
      - "8081:8080"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "7"
