spring.application.name=reminders

# MySQL (latest 8.x / 9.x connector compatible)
spring.datasource.url=${DB_URL:jdbc:mysql://reminders-db:3306/reminders?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root1}
spring.datasource.password=${DB_PASSWORD:Dzee2015$}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.sql.init.mode=always

# Email (SMTP)
#izcv acev lkyl vwyn
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:sr.aivante@gmail.com}
spring.mail.password=${MAIL_PASSWORD:izcvacevlkylvwyn}
app.mail.from=${MAIL_FROM:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SSL_TRUST:smtp.gmail.com}

# WhatsApp (Twilio)
app.whatsapp.twilio.account-sid=
app.whatsapp.twilio.auth-token=
app.whatsapp.twilio.from=${WHATSAPP_FROM:+14155238886}

# Run every minute
app.notification.cron=0 * * * * *
server.servlet.session.tracking-modes=cookie
