spring.application.name=reminders

# MySQL (latest 8.x / 9.x connector compatible)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/reminders?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME:root1}
spring.datasource.password=${DB_PASSWORD:Dzee2015$}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.sql.init.mode=always

# Email (SMTP)
#izcv acev lkyl vwyn
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:sr.aivante@gmail.com}
spring.mail.password=${MAIL_PASSWORD:izcvacevlkylvwyn}
app.mail.from=${MAIL_FROM:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SSL_TRUST:smtp.gmail.com}

# WhatsApp (Twilio)
app.whatsapp.twilio.account-sid=123
app.whatsapp.twilio.auth-token=EAAnb3q49HIUBQ0FlllpV5FMGte9L5ws5HBw58HD4SMFSb4GCJlyeXadAdZCbTu4LCoDITW9DOLhXy3BnDjGQ83ZAJHl7aLwjrl9ZAgx8wAKpQUj1nUkK92YedD7mWNYc3F4BAtMmfknEjUGR0Uo4WbBbXLUoX13iD0T8hRTZAXo2SXFHDz19cSd4Ig7SmQ7SMZClC9JSgcJ6LiPZAyc7umi46g5uLsoeiMfN1eN7lyV22zaOksIGBxXJxljHAS8rJ8UzCJPQhLlIfjdAbM42WO
app.whatsapp.twilio.from=${WHATSAPP_FROM:1025774503953615}

# Run every minute
app.notification.cron=0 * * * * *
server.servlet.session.tracking-modes=cookie
